sudo: required
language: java
jdk:
- oraclejdk8
script: mvn test -B -q
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "rc5ROLwdBRbJQrhcc1q44lToOTbFgusLyZKquQfYilyszhsWHBHZrqVWllIDJNsPMhPgqQr8Dyid9e+6pjyz67WPwIFi8/BRAq8hRKDmGgp9bRBlom4P5xLqQHsWQ4gohk+0r0laqR6t/tYg0LNpVhtfXF0ywQqPmFU+H3kFFegBQ5HiD9MfY36CWAakDl/Lagy3KEa4s8WHpcjyYq1F0q0RQDrp3SBfntGSAF0V2I4UxGKTxuS2fUKP1i7CzV9n7y77+VB2shGpSN58BMbhDiUL32b+CpBYORpIkaiP9nk3KDKRgP3/dFoCSzGfLu3mdmracVCuERInqqZj1cwe84oVpMhkNBKPVotI5y0ZG+YkzhDhKpbL0D93AXjFDZ5kmb58AMEw74j2649ZjuNI0ZuzcC7uXCDKLLQFeIZTg4e87qHJOTPmo2j0ReHBq2KkBz3pfE5YnMQu9ucHBWB6IAi8Gzi5lp7C70epBYGs7f27p3djTidvHzPebvPTLmOAaZhAh1swaJ/VM/dKN4VH6TBon54h4DAR6MbCJzoHPUPqxwGw5rR0eXtc0V8yPHc7OW+l0K87mOxFrtkGAju+A4MLb/Bbc00IV/JU9iHM1XNZn8NH1nJgYCh4YLZ59hMIV2R3zFTvfbgaFaYxINxUaPnLRd0gRyy55+bDi4/dpUc=" #DOCKER_USERNAME
  - secure: "IKYaqxegnKpsQjdh6d5hjmMvXwSm1vRcFXkGtUr5ZKbecX0ivkgXTHSH8znlz4GfqNflM5UQQ426B/XMOOx/sNRWGBYWOrNMqUCvSOCcmnYLAxO/sJPBQzCXFUDUNFqYlTBDQGkrNMzYBRr3zTSXybupR9JUOzRJ8VuXI+Azwq0081/8tVY04Ki4OA5S1NhZgzsnX6I+lFPoFYhEburbbt7kD9hnYTg+ZTPi0Ptk+Ara1GsKSKAOD+qsYZJqdqn8ejgKr3EW1J9iA9or7n5aTgQdTcYfKmbwRjBhFfjP0ylbynpw5Tf/Bze6PbwvXg15jByjEgBy43LOynrcpFfWkKr0r5KqJ1+ondG2vYYugYcHA+OBaHDP9J7Eanh6mr60Nfvl/+WM+EE3qqr3ekWQECYhvgZiXjj4orWXyf9TScGI6TLmm0QV/pbFv8Jg88ZqeoCVlA8ht33ojlVfH6drHQnrVHlJsFmFQW0/xfQnMunBvZVc3SoHHd78MqmvNxMoiddoEdMZ6Ssj5LI5XL1RMG1cUWM/qxjJmocunkA9oveJHff3LnMyt+RXpBzCOG8l7k5Kg7IdItcvEMDPGZwHHn58JOzkZpfNdJkAKGeVFscP27hTjDJFSiL24UAM5F/5ux+2H3LsIK0aPRSB7au7BSAAE/35GRQw9OLWs2L9HTk=" #DOCKER_PASSWORD
after_success:
- mvn test jacoco:report coveralls:report
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- export REPO=maxdemarzi/disoriented
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
